spring.application.name=dndcompanion

# MongoDB connection
spring.mongodb.uri=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@localhost:27017/dnd_app?authSource=admin

# Server port (default 8080)
server.port=8080

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000
